BoxLayoutExample:

<BoxLayoutExample>
    orientation: "vertical"
    Button:
        text: "A"
        size: "40dp", "40dp"
    Button:
        text: "B"
    Label:
        text: "C"

<MainWidget>:
    Button:
        text: "Hello"
        size: "40dp", "40dp"
        pos: "100dp", "200dp"
        color: 0, 0, 1, 1
    
    Label:
        text: "Hello2"
        size: "40dp", "40dp"
        pos: "200dp", "300dp"
        color: 1, 0, 0, 1